var library = JSON.parse(`
[
 {
  "Folder": "Brandon Sanderson/Edgedancer",
  "State": "Downloaded",
  "Title": "Edgedancer",
  "Series": "The Stormlight archive",
  "Book Number": "",
  "Author": "",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "James Dashner/The Eye of Minds",
  "State": "Downloaded",
  "Title": "The Eye of Minds",
  "Series": "The Mortality Doctrine",
  "Book Number": 1,
  "Author": "James Dashner",
  "Narrator": "Erik Davies",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "James Dashner/The Rule of Thoughts",
  "State": "Downloaded",
  "Title": "The Rule of Thoughts",
  "Series": "The Mortality Doctrine",
  "Book Number": 2,
  "Author": "James Dashner",
  "Narrator": "Erik Davies",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "James Dashner/Maze Runner Series/The Maze Runner",
  "State": "Downloaded",
  "Title": "The Maze Runner",
  "Series": "The Maze Runner Trilogy",
  "Book Number": 1,
  "Author": "James Dashner",
  "Narrator": "Mark Deakins",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "James Dashner/Maze Runner Series/The Scorch Trials",
  "State": "Downloaded",
  "Title": "The Scorch Trials",
  "Series": "The Maze Runner Trilogy",
  "Book Number": 2,
  "Author": "James Dashner",
  "Narrator": "Mark Deakins",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "James Dashner/Maze Runner Series/The Kill Order",
  "State": "Downloaded",
  "Title": "The Kill Order",
  "Series": "The Maze Runner Trilogy",
  "Book Number": 4,
  "Author": "James Dashner",
  "Narrator": "Mark Deakins",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "The Heir Chronicles/The Warrior Heir",
  "State": "Downloaded",
  "Title": "The Warrior Heir",
  "Series": "The Heir Chronicles",
  "Book Number": 1,
  "Author": "Cinda Williams Chima",
  "Narrator": "Robert Ramirez",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "The Heir Chronicles/The Wizard Heir",
  "State": "Downloaded",
  "Title": "The Wizard Heir",
  "Series": "The Heir Chronicles",
  "Book Number": 2,
  "Author": "Cinda Williams Chima",
  "Narrator": "Robert Ramirez",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "The Heir Chronicles/Dragon Heir",
  "State": "Downloaded",
  "Title": "Dragon Heir",
  "Series": "The Heir Chronicles",
  "Book Number": 3,
  "Author": "Cinda Williams Chima",
  "Narrator": "Robert Ramirez",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "The Heir Chronicles/The Enchanter Heir",
  "State": "Downloaded",
  "Title": "The Enchanter Heir",
  "Series": "The Heir Chronicles",
  "Book Number": 4,
  "Author": "Cinda Williams Chima",
  "Narrator": "Robert Ramirez",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "The Heir Chronicles/The Sorcerer Heir",
  "State": "Downloaded",
  "Title": "The Sorcerer Heir",
  "Series": "The Heir Chronicles",
  "Book Number": 5,
  "Author": "Cinda Williams Chima",
  "Narrator": "Robert Ramirez",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "Brandon Mull/The Five Kingdoms/Sky Raiders",
  "State": "Downloaded",
  "Title": "Sky Raiders",
  "Series": "The Five Kingdoms",
  "Book Number": 1,
  "Author": "Brandon Mull",
  "Narrator": "Keith Nobbs",
  "Publisher": "Simon and Schuster",
  "": ""
 },
 {
  "Folder": "Brandon Mull/The Five Kingdoms/The Rogue Knight",
  "State": "Downloaded",
  "Title": "The Rogue Knight",
  "Series": "The Five Kingdoms",
  "Book Number": 2,
  "Author": "Brandon Mull",
  "Narrator": "Keith Nobbs",
  "Publisher": "Simon and Schuster",
  "": ""
 },
 {
  "Folder": "Brandon Mull/The Five Kingdoms/Crystal Keepers",
  "State": "Downloaded",
  "Title": "Crystal Keepers",
  "Series": "The Five Kingdoms",
  "Book Number": 3,
  "Author": "Brandon Mull",
  "Narrator": "Keith Nobbs",
  "Publisher": "Simon and Schuster",
  "": ""
 },
 {
  "Folder": "Brandon Mull/The Five Kingdoms/Death Weavers",
  "State": "Downloaded",
  "Title": "Death Weavers",
  "Series": "The Five Kingdoms",
  "Book Number": 4,
  "Author": "Brandon Mull",
  "Narrator": "Keith Nobbs",
  "Publisher": "Simon and Schuster",
  "": ""
 },
 {
  "Folder": "39 Clues/Unstoppable/Nowhere to Run",
  "State": "Downloaded",
  "Title": "Nowhere to Run",
  "Series": "The 39 Clues: Unstoppable series",
  "Book Number": 1,
  "Author": "Jude Watson",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Unstoppable/Breakaway",
  "State": "Downloaded",
  "Title": "Breakaway",
  "Series": "The 39 Clues: Unstoppable series",
  "Book Number": 2,
  "Author": "Jeff Hirsh",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Unstoppable/Flashpoint",
  "State": "Downloaded",
  "Title": "Flashpoint",
  "Series": "The 39 Clues: Unstoppable series",
  "Book Number": 4,
  "Author": "Gordon Korman",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Superspecial/Outbreak",
  "State": "Downloaded",
  "Title": "Outbreak",
  "Series": "The 39 Clues: Superspecial series",
  "Book Number": 1,
  "Author": "C. Alexander London",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Original/The Sword Thief",
  "State": "Downloaded",
  "Title": "The Sword Thief",
  "Series": "The 39 Clues: Original series",
  "Book Number": 3,
  "Author": "Peter Lerangis",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Original/The Black Circle",
  "State": "Downloaded",
  "Title": "The Black Circle",
  "Series": "The 39 Clues: Original series",
  "Book Number": 5,
  "Author": "Patrick Caman",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Original/The Viper's Nest",
  "State": "Downloaded",
  "Title": "The Viper's Nest",
  "Series": "The 39 Clues: Original series",
  "Book Number": 7,
  "Author": "Peter Lerangis",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Original/Storm Warning",
  "State": "Downloaded",
  "Title": "Storm Warning",
  "Series": "The 39 Clues: Original series",
  "Book Number": 9,
  "Author": "Linda Sue Park",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Original/Vespers Rising",
  "State": "Downloaded",
  "Title": "Vespers Rising",
  "Series": "The 39 Clues: Original series",
  "Book Number": 11,
  "Author": "Rick Riordan",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Double Cross/Mission Titanic",
  "State": "Downloaded",
  "Title": "Mission Titanic",
  "Series": "The 39 Clues: Double cross series",
  "Book Number": 1,
  "Author": "Jude Watson",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Double Cross/Mission Hindenburg",
  "State": "Downloaded",
  "Title": "Mission Hindenburg",
  "Series": "The 39 Clues: Double cross series",
  "Book Number": 2,
  "Author": "C. Alexander London",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Double Cross/Mission Hurricane",
  "State": "Downloaded",
  "Title": "Mission Hurricante",
  "Series": "The 39 Clues: Double cross series",
  "Book Number": 3,
  "Author": "Jenny Goebel",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Double Cross/Mission Atomic",
  "State": "Downloaded",
  "Title": "Mission Atomic",
  "Series": "The 39 Clues: Double cross series",
  "Book Number": 4,
  "Author": "Sarwat Chadda",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Vespers/The Medusa Plot",
  "State": "Downloaded",
  "Title": "The Medusa Plot",
  "Series": "The 39 Clues: Cahills vs Vespers series",
  "Book Number": 1,
  "Author": "Gordon Korman",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Vespers/A King's Ransom",
  "State": "Downloaded",
  "Title": "A King's Ransom",
  "Series": "The 39 Clues: Cahills vs Vespers series",
  "Book Number": 2,
  "Author": "Jude Watson",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Vespers/Shatterproof",
  "State": "Downloaded",
  "Title": "Shatterproof",
  "Series": "The 39 Clues: Cahills vs Vespers series",
  "Book Number": 4,
  "Author": "Roland Smith",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Vespers/Trust No One",
  "State": "Downloaded",
  "Title": "Trust No One",
  "Series": "The 39 Clues: Cahills vs Vespers series",
  "Book Number": 5,
  "Author": "Linda Sue Park",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Vesperse/Day of Doom",
  "State": "Downloaded",
  "Title": "Day of Doom",
  "Series": "The 39 Clues: Cahills vs Vespers series",
  "Book Number": 6,
  "Author": "David Balacci",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "39 Clues/Cahill Files/Operation Trinity",
  "State": "Downloaded",
  "Title": "Operation Trinity",
  "Series": "The 39 Clues: Cahills Files Series",
  "Book Number": 1,
  "Author": "Clifford Riley",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "Terry Pratchet/Dragons at Crumbling Castle",
  "State": "Downloaded",
  "Title": "Dragons at Crumbling Castle",
  "Series": "Single Book",
  "Book Number": 1,
  "Author": "Terry Pratchett",
  "Narrator": "Julian Rhind-tutt",
  "Publisher": "Penguin",
  "": ""
 },
 {
  "Folder": "L Ron Hubbard/Sabotage in the Sky",
  "State": "Downloaded",
  "Title": "Sabotage in the Sky",
  "Series": "Single Book",
  "Book Number": 1,
  "Author": "L. Ron Hubbard",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "Shattered Realms/Flamecaster",
  "State": "Downloaded",
  "Title": "Flamecaster",
  "Series": "Shattered Realms",
  "Book Number": 1,
  "Author": "Cinda Williams Chima",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "Shattered Realms/Shadowcaster",
  "State": "Downloaded",
  "Title": "Shadowcaster",
  "Series": "Shattered Realms",
  "Book Number": 2,
  "Author": "Cinda Williams Chima",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "Real Mermaids/Real Mermaids Don't Wear Toe Rings",
  "State": "Downloaded",
  "Title": "Real Mermaids Don't Wear Toe Rings",
  "Series": "Real Mermaids",
  "Book Number": 1,
  "Author": "Helen Boudreau",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "Orson Scott Card/The Gate Thief",
  "State": "Downloaded",
  "Title": "The Gate Thief",
  "Series": "Mither Mages",
  "Book Number": 2,
  "Author": "Orson Scott Card",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "James Patternson/The Final Warning",
  "State": "Downloaded",
  "Title": "The Final Warning",
  "Series": "Maximum Ride",
  "Book Number": 4,
  "Author": "James Patterson",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "Ursula K LaGuin/A Wizard of EarthSea",
  "State": "Downloaded",
  "Title": "A Wizard of EarthSea",
  "Series": "EarthSea",
  "Book Number": 1,
  "Author": "Ursula K. Le Guin",
  "Narrator": "Rob Inglis",
  "Publisher": "Recorded Books",
  "": ""
 },
 {
  "Folder": "Ursula K LaGuin/The Farthest Shore",
  "State": "Downloaded",
  "Title": "The Farthest Shore",
  "Series": "EarthSea",
  "Book Number": 3,
  "Author": "Ursula K. Le Guin",
  "Narrator": "Rob Inglis",
  "Publisher": "Recorded Books",
  "": ""
 },
 {
  "Folder": "Ursula K LaGuin/The Tombs of Atuan",
  "State": "Downloaded",
  "Title": "The Tombs of Atuan",
  "Series": "EarthSea",
  "Book Number": 2,
  "Author": "Ursula K. Le Guin",
  "Narrator": "Rob Inglis",
  "Publisher": "Recorded Books",
  "": ""
 },
 {
  "Folder": "39 Clues/Original/Into the Gauntlet",
  "State": "Downloaded",
  "Title": "Into the Gauntlet",
  "Series": "The 39 Clues: Original series",
  "Book Number": 10,
  "Author": "Margaret Peterson Haddix",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "Jenny Nimmo/Charlie Bone and the Time Twister",
  "State": "Downloaded",
  "Title": "The Time Twister",
  "Series": "Charlie Bone and the Children of the Red King",
  "Book Number": 2,
  "Author": "Jenny Nimmo",
  "Narrator": "Simon Russell Beale",
  "Publisher": "Penguin",
  "": ""
 },
 {
  "Folder": "Jenny Nimmo/Charlie Bone and the Invisible Boy",
  "State": "Downloaded",
  "Title": "Charlie Bone and the Invisible Boy",
  "Series": "Charlie Bone and the Children of the Red King",
  "Book Number": 3,
  "Author": "Jenny Nimmo",
  "Narrator": "Simon Russell Beale",
  "Publisher": "Penguin",
  "": ""
 },
 {
  "Folder": "Jenny Nimmo/Charlie Bone and the Hidden King",
  "State": "Downloaded",
  "Title": "Charlie Bone and the Hidden King",
  "Series": "Charlie Bone and the Children of the Red King",
  "Book Number": 5,
  "Author": "Jenny Nimmo",
  "Narrator": "Simon Russell Beale",
  "Publisher": "Penguin",
  "": ""
 },
 {
  "Folder": "Jenny Nimmo/Charlie Bone and the Beast",
  "State": "Downloaded",
  "Title": "Charlie Bone and the Beast",
  "Series": "Charlie Bone and the Children of the Red King",
  "Book Number": 6,
  "Author": "Jenny Nimmo",
  "Narrator": "Simon Jones",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "Jenny Nimmo/Charlie Bone and the Shadow",
  "State": "Downloaded",
  "Title": "Charlie Bone and the Shadow",
  "Series": "Charlie Bone and the Children of the Red King",
  "Book Number": 7,
  "Author": "Jenny Nimmo",
  "Narrator": "Simon Jones",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "Missing",
  "Title": "The Snow Spider",
  "Series": "The Magician Trilogy",
  "Book Number": 1,
  "Author": "Jenny Nimmo",
  "Narrator": "John Keating",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "Missing",
  "Title": "Emlyn's Moon",
  "Series": "The Magician Trilogy",
  "Book Number": 2,
  "Author": "Jenny Nimmo",
  "Narrator": "John Keating",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "Missing",
  "Title": "The Chestnut Soldier",
  "Series": "The Magician Trilogy",
  "Book Number": 3,
  "Author": "Jenny Nimmo",
  "Narrator": "John Keating",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "Missing",
  "Title": "The Dragon's Child and the Night of the Unicorn",
  "Series": "Single Book",
  "Book Number": 1,
  "Author": "Jenny Nimmo",
  "Narrator": "John Keating",
  "Publisher": "Oakhill Publishing",
  "": ""
 },
 {
  "Folder": "",
  "State": "Missing",
  "Title": "The Secret Kingdom",
  "Series": "Chronicles of the Red King",
  "Book Number": 1,
  "Author": "Jenny Nimmo",
  "Narrator": "John Keating",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "Missing",
  "Title": "The Stones of Ravenglass",
  "Series": "Chronicles of the Red King",
  "Book Number": 2,
  "Author": "Jenny Nimmo",
  "Narrator": "John Keating",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "Missing",
  "Title": "Leopards' Gold",
  "Series": "Chronicles of the Red King",
  "Book Number": 3,
  "Author": "Jenny Nimmo",
  "Narrator": "John Keating",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "Jenny Nimmo/Midnight for Charlie Bone",
  "State": "Missing",
  "Title": "Midnight for Charlie Bone",
  "Series": "Charlie Bone and the Children of the Red King",
  "Book Number": 1,
  "Author": "Jenny Nimmo",
  "Narrator": "Simon Russell Beale",
  "Publisher": "Penguin",
  "": ""
 },
 {
  "Folder": "Jenny Nimmo/Charlie Bone and the",
  "State": "Missing",
  "Title": "The Castle of Mirrors",
  "Series": "Charlie Bone and the Children of the Red King",
  "Book Number": 4,
  "Author": "Jenny Nimmo",
  "Narrator": "Simon Russell Beale",
  "Publisher": "Penguin",
  "": ""
 },
 {
  "Folder": "39 Clues/Vespers/The Dead of Night",
  "State": "none",
  "Title": "The Dead of Night",
  "Series": "The 39 Clues: Cahills vs Vespers series",
  "Book Number": 3,
  "Author": "Peter Lerangis",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "none",
  "Title": "The Death Cure",
  "Series": "The Maze Runner Trilogy",
  "Book Number": 3,
  "Author": "James Dashner",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "",
  "State": "none",
  "Title": "The Fever Code",
  "Series": "The Maze Runner Trilogy",
  "Book Number": 5,
  "Author": "James Dashner",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "",
  "State": "none",
  "Title": "The Maze of Bones",
  "Series": "The 39 Clues: Original series",
  "Book Number": 1,
  "Author": "",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "none",
  "Title": "In Too Deep",
  "Series": "The 39 Clues: Original series",
  "Book Number": 6,
  "Author": "",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "none",
  "Title": "The Lost Gate",
  "Series": "Mither Mages",
  "Book Number": 1,
  "Author": "Orson Scott Card",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "",
  "State": "none",
  "Title": "Gatefather",
  "Series": "Mither Mages",
  "Book Number": 3,
  "Author": "Orson Scott Card",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "",
  "State": "On Hold",
  "Title": "The Game of Lives",
  "Series": "The Mortality Doctrine",
  "Book Number": 3,
  "Author": "James Dashner",
  "Narrator": "",
  "Publisher": "",
  "": ""
 },
 {
  "Folder": "",
  "State": "On Hold",
  "Title": "Countdown",
  "Series": "The 39 Clues: Unstoppable series",
  "Book Number": 3,
  "Author": "",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "On Hold",
  "Title": "One False Note",
  "Series": "The 39 Clues: Original series",
  "Book Number": 2,
  "Author": "",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "On Hold",
  "Title": "Beyond the Grave",
  "Series": "The 39 Clues: Original series",
  "Book Number": 4,
  "Author": "",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "On Hold",
  "Title": "The Emperor's Code",
  "Series": "The 39 Clues: Original series",
  "Book Number": 8,
  "Author": "Gordon Korman",
  "Narrator": "David Pittu",
  "Publisher": "Scholastic Audio",
  "": ""
 },
 {
  "Folder": "",
  "State": "On Hold",
  "Title": "Charlie Bone and the Red Knight",
  "Series": "Charlie Bone and the Children of the Red King",
  "Book Number": 8,
  "Author": "Jenny Nimmo",
  "Narrator": "",
  "Publisher": "Scholastic Audio",
  "": ""
 }
]`);
